### ISSUE TITLE
Crash app when starting

### ISSUE THREAD

**Issue by mikhaillazko** [Pushwoosh/pushwoosh-mac-sdk#1]
I use framework in my app and i have crash when application starting. It's not periodical crash, I got such a mistake twice. How i can disable automatic initialization pushManager and registration app when app starting? attach log file
[ReportLog.txt](https://github.com/Pushwoosh/pushwoosh-mac-sdk/files/197258/ReportLog.txt)

**Comment by shaders** [comment]
Hi,

We've just pushes HUGE update to the Mac SDK.

There's also a new guide:
http://docs.pushwoosh.com/v1.0/docs/mac-os-x-push-notification-sdk

And updated sample!
https://github.com/Pushwoosh/pushwoosh-mac-sdk/tree/master/Samples/Mac

Let me know if new SDK works for you!
