### ISSUE TITLE
Support for M1

### ISSUE THREAD

**Issue by DenTelezhkin** [Pushwoosh/pushwoosh-mac-sdk#3]
Hi!

Currently Pushwoosh supports only x86_64 architecture, which can be validated by running (6.2.1 version manually or from CocoaPods):

```
lipo -info Pushwoosh
Non-fat file: Pushwoosh is architecture: x86_64
```

This makes Pushwoosh unusable on Apple Silicon Macs. Are there any plans to support M1?

**Comment by wfhm** [comment]
@DenTelezhkin,

Fixed with the latest release.
